version: '3.8'

services:
  ffc-grants-file-sender:
    build:
      context: .
      target: production
    image: ffc-grants-file-sender
    container_name: ffc-grants-file-sender
    environment:
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      FILE_CREATED_SUBSCRIPTION_ADDRESS: ${FILE_CREATED_SUBSCRIPTION_ADDRESS:-notset}
      FILE_CREATED_TOPIC_ADDRESS: ${FILE_CREATED_TOPIC_ADDRESS:-notset}
      BLOB_STORAGE_CONNECTION_STRING: ${BLOB_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=https;AccountName=dummy;AccountKey=dummy;EndpointSuffix=core.windows.net}
      BLOB_STORAGE_CONTAINER_NAME: ${BLOB_STORAGE_CONTAINER_NAME:-notset}
      BLOB_STORAGE_CONNECTION_STRING: ${BLOB_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=https;AccountName=dummy;AccountKey=dummy;EndpointSuffix=core.windows.net}
      USE_BLOB_STORAGE_CONNECTION_STRING: "true"
      SHAREPOINT_SITE_ID: ${SHAREPOINT_SITE_ID:-notset}
      SHAREPOINT_TENANT_ID: ${SHAREPOINT_TENANT_ID:-notset}
      SHAREPOINT_CLIENT_ID: ${SHAREPOINT_CLIENT_ID:-notset}
      SHAREPOINT_CLIENT_SECRET: ${SHAREPOINT_CLIENT_SECRET:-notset}
      SHAREPOINT_DOCUMENT_LIBRARY_ID: ${SHAREPOINT_DOCUMENT_LIBRARY_ID:-notset}
