version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-grants-file-sender:
    build:
      target: development
    image: ffc-grants-file-sender-development
    container_name: ffc-grants-file-sender-development
    ports:
      - "3005:3000"
      - "9234:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
