version: '3.8'

services:
  ffc-grants-file-sender:
    build:
      context: .
      target: production
    image: ffc-grants-file-sender
    container_name: ffc-grants-file-sender
    environment: {}
